FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Microservice2.API/Microservice2.API.csproj", "Microservice2.API/"]
COPY ["SessionProjects.ServiceDefaults/SessionProjects.ServiceDefaults.csproj", "SessionProjects.ServiceDefaults/"]
COPY ["SessionProjects.Contracts/SessionProjects.Contracts.csproj", "SessionProjects.Contracts/"]
RUN dotnet restore "Microservice2.API/Microservice2.API.csproj"
COPY . .
WORKDIR "/src/Microservice2.API"
RUN dotnet build "./Microservice2.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Microservice2.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservice2.API.dll"]
