<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>76dc0fdc-fcaf-43f6-8b47-9ee29119cce6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Microservice1.API\Microservice1.API.csproj" />
      <ProjectReference Include="..\Microservice2.API\Microservice2.API.csproj" />
      <ProjectReference Include="..\ObservabilityAgent\ObservabilityAgent.csproj" />
      <ProjectReference Include="..\KubernetesAgent\KubernetesAgent.csproj" />
      <ProjectReference Include="..\SreAdvisorAgent\SreAdvisorAgent.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.4" />
    </ItemGroup>

</Project>
